baseURL: https://toha.netlify.app

languageCode: en-us
title: "Toha"
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true

# Enable Google Analytics
googleAnalytics: UA-122321624-2

# Enable Disqus forum
disqusShortname: toha-example-site

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  gitRepo: https://github.com/hossainemruz/toha-example-site
