baseURL: http://example.org/
languageCode: en-us
title: "Toha"
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true

# Enable Google Analytics
googleAnalytics: UA-123-45

# Enable Disqus forum
disqusShortname: hossainemruz-github-io

# Enable global emoji support
enableEmoji: true
