name: Test Lighthouse Check
on: [pull_request]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    # Run Lighthouse check
    - name: Run Lighthouse
      uses: foo-software/lighthouse-check-action@master
      id: lighthouseCheck
      with:
        accessToken: ${{ secrets.LIGHTHOUSE_TOKEN }}
        emulatedFormFactor: 'all'
        prCommentEnabled: true
        urls: 'https://toha.netlify.app'

    # Verify Lighthouse scores
    - name: Verify Lighthouse  scores
      uses: foo-software/lighthouse-check-status-action@master
      with:
        lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
        minAccessibilityScore: "95"
        minBestPracticesScore: "85"
        minPerformanceScore: "60"
        minProgressiveWebAppScore: "50"
        minSeoScore: "90"
