name: Lighthouse
# Run check on pull request
on: [pull_request]

jobs:
  score-check:
    runs-on: ubuntu-latest
    steps:
    - name: Waiting for Netlify Preview
      uses: kamranayub/wait-for-netlify-action@v2.1.1
      id: preview
      with:
        site_name: "toha-guides"
        max_timeout: 60
      env:
        NETLIFY_TOKEN: ${{secrets.NETLIFY_TOKEN}}

    # Run Lighthouse check
    - name: Run Lighthouse
      uses: foo-software/lighthouse-check-action@v9.1.0
      id: lighthouseCheck
      with:
        accessToken: ${{ secrets.LIGHTHOUSE_TOKEN }}
        gitHubAccessToken: ${{secrets.GITHUB_TOKEN}}
        emulatedFormFactor: 'all'
        prCommentEnabled: true
        urls: "${{ steps.preview.outputs.url }},${{ steps.preview.outputs.url }}/posts/,${{ steps.preview.outputs.url }}/posts/writing-posts/markdown-syntax/"

    # - name: Comment Lighthouse scores
    #   uses: marocchino/sticky-pull-request-comment@v2
    #   if:  ${{ steps.lychee.outputs.exit_code }} != 0
    #   with:
    #     message: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
