name: Lighthouse
on: [pull_request]

jobs:
  score-check:
    runs-on: ubuntu-latest
    steps:
    # Wait for the preview deployed by Netlify
    - name: Wait for preview deployed
      uses: fountainhead/action-wait-for-check@master
      id: wait-for-preview
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: netlify/toha/deploy-preview
        ref: ${{ github.event.pull_request.head.sha || github.sha }}

    # Run Lighthouse check
    - name: Run Lighthouse
      uses: foo-software/lighthouse-check-action@master
      id: lighthouseCheck
      with:
        accessToken: ${{ secrets.LIGHTHOUSE_TOKEN }}
        emulatedFormFactor: 'all'
        prCommentEnabled: true
        urls: "https://deploy-preview-${{github.event.issue.number}}--toha.netlify.app,https://deploy-preview-${{github.event.issue.number}}--toha.netlify.app/posts/,https://deploy-preview-${{github.event.issue.number}}--toha.netlify.app/posts/writing-posts/markdown-syntax-guide/"

    # Verify Lighthouse scores
    - name: Verify Lighthouse  scores
      uses: foo-software/lighthouse-check-status-action@master
      with:
        lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
        minAccessibilityScore: "95"
        minBestPracticesScore: "85"
        minPerformanceScore: "60"
        minProgressiveWebAppScore: "50"
        minSeoScore: "90"
