name: Check Markdown links

# Run action on pull request event
on: [pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    # checkout to latest commit
    - uses: actions/checkout@master
    # run markdown linter
    - uses: BoundfoxStudios/action-hugo-link-check@v2
      with:
        timeout: 300
        fail-on-broken-links: 0
        hugo-startup-wait-time: 60
        hugo-root: ./
        hugo-content-dir: ./content
        hugo-config: ./config.yaml
