name: Check Markdown links

# Run action on pull request event
on: [pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    # checkout to latest commit
    - uses: actions/checkout@master
    # run markdown linter
    - uses: BoundfoxStudios/action-hugo-link-check@v2
      with:
        timeout: 300
        # hugo-root: docs
        # hugo-content-dir: docs/content
        # hugo-config: docs/config.yaml
