name: Check Markdown links

# Run action on pull request event
on: [pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    # checkout to latest commit
    - uses: actions/checkout@master

    - name: Waiting for Netlify Preview
      uses: josephduffy/wait-for-netlify-action@v1
      id: netflify-preview
      with:
        site_name: "toha-guides"
        max_timeout: 120

    - name: Link Checker
      id: lychee
      uses: lycheeverse/lychee-action@v1.5.4
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        args: "--verbose ${{steps.netlify-preview.url}}"

    - name: Comment Broken Links
      uses: marocchino/sticky-pull-request-comment@v2
      if: env.lychee_exit_code != 0
      with:
        path: ./lychee/out.md
