name: Check Markdown links

# Run action on pull request event
on: [pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    # checkout to latest commit
    - uses: actions/checkout@master
    # run markdown linter
    - uses: BoundfoxStudios/action-hugo-link-check@v2
      id: link-check
      continue-on-error: true
      with:
        timeout: 300
        fail-on-broken-links: 0
        hugo-startup-wait-time: 120
        hugo-root: ./
        hugo-content-dir: ./content
        hugo-config: ./config.yaml
    - name: "Print Broken Links"
      run: |
        BROKEN_LINK_COUNT="${{ steps.link-check.outputs.broken-links-count }}"
        if [[ "$BROKEN_LINK_COUNT" -gt 0 ]]; then
          echo ${{ steps.link-check.outputs.broken-links}}
          exit 1
        else
          echo "No broken link found"
          exit 0
        fi
